sudo: required
services:
    - docker

before_install:
    - docker build -t tahifamed/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tahifamed/docker-react npm run test

deploy:
    provider : elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-577228747206"
    bucket_pack: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

        